version: '3'
services:
  postgres:
    container_name: app
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
       - "5432:5432"
